### PR TITLE
Featureset5 merge with master #2

### PR DESCRIPTION
**Pull request by hgamiel**
Hey all, I've grabbed everyone's commits since the first pull request went through and merged them with featureset5 again. If everyone's ok with this, I'd love to merge featureset5 with master again so that master can contain those updated changes made today. Please write "ok"/"yes" if this is good with you and your team.

### CODE REVIEW

**Comment by hgamiel** [comment]
This pull request will be merged with master by 10:00pm tonight. Please comment if the code in FeatureSet5's branch (this branch) has any code differing from code you have updated yourselves. The code contained has been updated with all code changes prior to 8:30pm today (Tuesday).

**Comment by jhoole** [comment]
FeatureSet4 is still in the middle of updating.
(I also accidentally pushed some files to master. Hopefully that won't hurt anything...)

**Comment by jhoole** [comment]
Okay, FeatureSet4 should be done as of 8:48 pm.

**Comment by hgamiel** [comment]
Ok, the code in FeatureSet5 has been updated to reflect all updated code prior to 8:51pm. Jenna: Not a problem!

**Comment by hgamiel** [comment]
Alright, it's 10:00: The merge will be happening now. Speak now, or forever hold your peace!

**Pull request merged**
