### PR TITLE
Featureset5 merge with master

### PR DESCRIPTION
**Pull request by hgamiel**
Featureset5 currently has everyone's changes up to 3:20pm on Thursday, April 2nd. If we can merge with master, then master will have everyone's updated files. This way, everyone can pull from master within the next couple of days to update their branches to be have everyone's changes. This will avoid future conflicts when everyone and their mother decides to make a pull request to master at once.

### CODE REVIEW

**Comment by hgamiel** [comment]
Please comment with your featureset # and whether or not you approve of this pull request!

**Comment by tglasser15** [comment]
we approve: featureset 2

**Comment by timothy** [comment]
Approved (featureset 1) but we recently updated login.php, login.html, and editConsultant.php in master (since 3:20) if you want to leave those out?

**Comment by hgamiel** [comment]
Hey all! This branch has now been updated to everyone's latest commits by the time of 10:06 on April 6th. Please comment saying "Yes, good to go" to this pull request if you think it should be merged with master. Things might not be perfect, so please check the files in this branch (more specifically, the ones you have edited) before saying it's OK. If not, please let me know so I can make the necessary changes to the files before this is merged with master.

**Comment by hgamiel** [comment]
FeatureSet3 says ok!

**Comment by hgamiel** [comment]
FeatureSet5 also says ok! (obviously)

**Comment by jhoole** [comment]
php/postConsultation.php is different than the FeatureSet4 version as it appears Tommy's been working on it, but other than that, everything with FeatureSet4 appears up to date based on commit history.

**Comment by tglasser15** [comment]
FeatureSet2 ok

**Comment by hgamiel** [comment]
Alright. Everyone has approved of this pull request with the exception of FeatureSet1, but they haven't committed anything to their branch since Thursday afternoon, and I already have those changes merged with FeatureSet5's branch. If there are any objections to this pull request... speak now or forever hold your peace!

**Comment by alex-4** [comment]
Our most recent changes are whatever Josh was saying he merged with master earlier so I think we are also ok (featureset1)

**Comment by hgamiel** [comment]
Alright. FeatureSet5 has merged with master! Master now has everyone's updated code. Thanks, everyone!

**Pull request merged**
